# .travis.yml

language: node_js
node_js:
  - node
addons:
  chrome: stable
deploy:
  provider: heroku
  app: blaise2s
  api_key:
    secure: U3TymZg+MnPoTlfeCziWVIiCH3jKDzHjo6aQTXe0yKPNE98VZ/vz++72grfUw2UVykjs6hqjSd0cH2UkWsjIphA09WPQL4BRxnLNzNHVZUpCcsxrrvUcD46WBPAVUWHsgA3xHVIbT2Y8ua1zyS3Y6K1wiUXYI/zs9rWD/NfC7uknVpSvfBFF6YZYmPxUrts4fbaEDgNSFo55+fWupVXDaVrw8j9Fy7jZNZynOQuRONQHIv3JL85y9raOnxV9vwYMu/e2REm6OJjQhhxVK17ymGh8x0YxiERnHUs5W65fMWCMqL8hw/1gDIp4JsB0JNCc39Uj6Axo8BWbNeAzvioppXphwYECkyNl8h5wH4aIO+ju9qqTbFbO5yO8kdrQUm/tsj5/jINBbceqBnKYaqkiP6rDcR2qcTg9dHrY7be7v3Z40GjzaIZRBLceaFmAoV/bhOTHBzCrNUS0eIeYGd3xAs96X00OPf1MVrgZ6gI6m7jwZuup/bmnFzsJxYryP7mb6q71X/C/T6DJkv5sv3pFqUKIgbRTVKTkHpI+PLbYLx6n7cTC1IaLmTAuNJRiNdshhDOZEGbI77I2cH75EQDfRFa704GOm1fzBQfJJC4lqxnX6aj3uN/7UTL2UkT+dwefzp/YKTORNwoqWC1fXok9dNXI0Fzozpz6hKb2Rbx/ZYA=
script:
  - npm run all-tests
  - npm run build
